FROM python:3.7
EXPOSE 8501
WORKDIR /app
COPY requirements.txt ./requirements.txt
RUN pip3 install -r requirements.txt
RUN pip3 install -U nltk
RUN pip3 install -U plotly
RUN pip3 install -U bs4
RUN pip3 install -U lxml
RUN pip3 install -U streamlit
COPY . /app
ENTRYPOINT ["streamlit","run"]
CMD ["app.py"]

